apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: mysql
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/image.dockerRepositoryCheck: 2018-07-19T08:05:35Z
    creationTimestamp: null
    generation: 2
    labels:
      app: mysql-55-centos7
    name: mysql-55-centos7
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: openshift/mysql-55-centos7
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/new-dev/mysql-55-centos7:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
