apiVersion: v1
kind: BuildConfig
parameters:
- displayName: Project Name
  value: openshift-django
  name: PROJECT_NAME
- displayName: Stage Server
  value: stage
  name: STAGE_SERVER
- displayName: Test Server
  value: test
  name: TEST_SERVER
metadata:
  name: myfirstpipeline
  labels:
    name: myfirstpipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "${PROJECT_NAME}", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
    jenkinsfile: |-
          pipeline {
            agent {
              label 'python'
            }
            stages {
              stage('Build App') {
                steps {
                  git branch: 'develop', url: 'https://github.com/ruddra/openshift-django.git'

                  sh "./run-build.sh"
                }
              }
              stage('Test') {
                steps {
                  sh "./run-tests.sh"
                }
              }
              stage('Code Analysis') {
                steps {
                  script {
                    sh "sonar:sonar -Dsonar.host.url=http://sonarqube:9000 -Dsonar.sources=."
                  }
                }
              }
              stage 'buildInDevelopment' {
                openshiftBuild(namespace: '${TEST_SERVER}', buildConfig: 'myapp', showBuildLogs: 'true')
              }
              

              
