apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: openshift-django
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: openshift-django
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: openshift-django:latest
    runPolicy: Serial
    source:
      git:
        ref: develop
        uri: https://github.com/ruddra/openshift-django.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.6
          namespace: openshift
      type: Docker
    postCommit:
      script: "python manage.py test"


- apiVersion: v1
  kind: ImageStream
  metadata:
    name: openshift-django

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mysql-55-centos7
    name: mysql-55-centos7
    resourceVersion: '219015'
    uid: c21278ce-8bf8-11e8-a514-080027f414e3
  spec:
    clusterIP: 172.30.162.176
    ports:
      - name: 3306-tcp
        port: 3306
        protocol: TCP
        targetPort: 3306
    selector:
      app: mysql-55-centos7
      deploymentconfig: mysql-55-centos7
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}


- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: mysql-55-centos7
  spec:
    replicas: 1
    selector:
      app: mysql-55-centos7
      deploymentconfig: mysql-55-centos7
    strategy:
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mysql-55-centos7
          deploymentconfig: mysql-55-centos7
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            value: myroot
          - name: MYSQL_PASSWORD
            value: myroot123
          - name: MYSQL_DATABASE
            value: mydjango
          image: openshift/mysql-55-centos7@sha256:7cd33ccc63b8005810aedee0444472cc84c3e3c38fe9cd147edb964e712a1068
          imagePullPolicy: Always
          name: mysql-55-centos7
          ports:
          - containerPort: 3306
            protocol: TCP


# - apiVersion: batch/v1
#   kind: Job
#   metadata:
#     name: od-add-vol
#   spec:
#     activeDeadlineSeconds: 400
#     completions: 1
#     parallelism: 1
#     template:
#       spec:
#         containers:
#         - env:
#           command:
#           - /bin/bash
#           - -x
#           - -c
#           - |
#             oc new-app openshift/mysql-55-centos7 \
#                 -e MYSQL_USER=myroot \
#                 -e MYSQL_PASSWORD=myroot123 \
#                 -e MYSQL_DATABASE=mydjango \

#             oc volume dc/openshift-django --mount-path='/data'

#           image: openshift/origin:v3.9.0
#           name: od-add-vol
#           resources: {}
#           terminationMessagePath: /dev/termination-log
#           terminationMessagePolicy: File
#         restartPolicy: Never