apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: openshift-django
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: openshift-django
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: openshift-django:latest
    runPolicy: Serial
    source:
      git:
        ref: develop
        uri: https://github.com/ruddra/openshift-django.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.6
          namespace: openshift
      type: Docker
    postCommit:
      script: "python manage.py test"


- apiVersion: v1
  kind: ImageStream
  metadata:
    name: openshift-django

- apiVersion: batch/v1
  kind: Job
  metadata:
    name: od-add-vol
  spec:
    activeDeadlineSeconds: 400
    completions: 1
    parallelism: 1
    template:
      spec:
        containers:
        - env:
          command:
          - /bin/bash
          - -x
          - -c
          - |
            oc volume dc/openshift-django --mount-path='/data'

          image: openshift/origin:v3.9.0
          name: od-add-vol
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        restartPolicy: Never