apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: openshift-django
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    generation: 2
    labels:
      app: openshift-django
    name: python
    uid: 673706ae-8c52-11e8-93af-e2ee266d1f70
  spec:
    lookupPolicy:
      local: false
    tags:
      - annotations:
          openshift.io/imported-from: 'python:3.6'
        from:
          kind: DockerImage
          name: 'python:3.6'
        generation: 2
        importPolicy: {}
        name: '3.6'
        referencePolicy:
          type: Source

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: openshift-django
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: openshift-django:latest
    runPolicy: Serial
    source:
      git:
        ref: develop
        uri: https://github.com/ruddra/openshift-django.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.6
          namespace: openshift
      type: Docker
    postCommit:
script: "python manage.py test"

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: openshift-django

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: openshift-django
    name: openshift-django
  spec:
    replicas: 0
    revisionHistoryLimit: 10
    selector:
      app: openshift-django
      deploymentconfig: openshift-django
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: openshift-django
          deploymentconfig: openshift-django
      spec:
        containers:
        - image: openshift-django:latest
          imagePullPolicy: Always
          name: openshift-django
          ports:
          - containerPort: 3013
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        containerNames:
        - openshift-django
        from:
          kind: ImageStreamTag
          name: openshift-django:latest
          namespace: new-dev
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: openshift-django
    name: openshift-django
  spec:
    ports:
    - name: 3013-tcp
      port: 3013
      protocol: TCP
      targetPort: 3013
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: openshift-django
      deploymentconfig: openshift-django
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mysql-55-centos7
    name: mysql-55-centos7
    uid: c21278ce-8bf8-11e8-a514-080027f414e3
  spec:
    clusterIP: 172.30.0.30
    ports:
      - name: 3306-tcp
        port: 3306
        protocol: TCP
        targetPort: 3306
    selector:
      app: mysql-55-centos7
      deploymentconfig: mysql-55-centos7
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}


- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: mysql-55-centos7
  spec:
    replicas: 1
    selector:
      app: mysql-55-centos7
      deploymentconfig: mysql-55-centos7
    strategy:
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mysql-55-centos7
          deploymentconfig: mysql-55-centos7
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            value: myroot
          - name: MYSQL_PASSWORD
            value: myroot123
          - name: MYSQL_DATABASE
            value: mydjango
          image: openshift/mysql-55-centos7@sha256:7cd33ccc63b8005810aedee0444472cc84c3e3c38fe9cd147edb964e712a1068
          imagePullPolicy: Always
          name: mysql-55-centos7
          ports:
          - containerPort: 3306
            protocol: TCP